export const EMOJI_TO_ICON: Record<string, import('./AppIcon').AppIconName> = {
  '🏠': 'place',
  '📚': 'books',
  '⭐': 'star',
  '💖': 'care',
  '❤️': 'care',
  '👑': 'crown',
  '✨': 'sparkles',
  '🔍': 'search',
  '🎛️': 'filters',
  '🎚️': 'filters',
  '💡': 'idea',
  '⏱️': 'timer',
  '🕒': 'time',
  '⏰': 'time',
  '📷': 'camera',
  '📆': 'calendar',
  '▶️': 'play',
  '🔗': 'share',
  '⬇️': 'download',
  '✔️': 'check',
  '❌': 'x',
};
